kind: pipeline
name: staging

platform:
  os: linux
  arch: amd64

steps:
  - name: publish_app_release
    pull: always
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
          repo: registry-intl.ap-southeast-5.aliyuncs.com/covid-detector/covid-detector-dicom-viewer
          tags: latest
      registry: registry-intl.ap-southeast-5.aliyuncs.com
    when:
      branch: develop
      event: push